This is a notebook about preparing twitch data for visualization. The dataset is available at https://github.com/sonnynomnom/Codecademy-Learn-SQL-from-Scratch/tree/master/Twitch

In [1]:
# Some important imports 

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
stream = pd.read_csv('stream.csv')
stream.head()

,time,device_id,login,channel,country,player,game,stream_format,subscriber
0,2015-01-01 18:33:52,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN
1,2015-01-01 23:35:33,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False
2,2015-01-01 04:39:38,2f9c3f9ee1033b71a3819564243f20ef3bec0183,5b9a43e68f019185f55615d0b83019dee4b5d06f,frank,US,site,League of Legends,chunked,False
3,2015-01-01 11:15:30,0cda8226ba2583424c80c3c1c22c1256b080ad17,02c7797faa4d8a3ff4b0c14ee1764b6817b53d0b,estelle,CH,site,Dota 2,high,False
4,2015-01-01 11:28:19,e3288ca5e3153aa85e32f64cdd994b7666968dcf,b920c228acbcbebee26d9c79f6eb73b73a9480c7,morty,FR,site,Heroes of the Storm,medium,False

In [3]:
stream.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526299 entries, 0 to 526298
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   time           526299 non-null  object
 1   device_id      526271 non-null  object
 2   login          526299 non-null  object
 3   channel        526299 non-null  object
 4   country        509135 non-null  object
 5   player         526299 non-null  object
 6   game           523175 non-null  object
 7   stream_format  267332 non-null  object
 8   subscriber     273814 non-null  object
dtypes: object(9)
memory usage: 36.1+ MB

In [4]:
chat = pd.read_csv('chat.csv')
chat.head()

,time,device_id,login,channel,country,player,game
0,2015-01-01 18:45:50,70e2b95b5ac0d4c227e46966658d16b3e044996e,5c2f5c1f19a7738e16ed0be551d865e8a8fce71d,jerry,BY,NaN,Dota 2
1,2015-01-01 01:16:57,f2b9065b55fd80d6aa653ce989b489f4ec5198be,0d77740e4fb5ce77d94f9f6c8ef1f762990d0344,elaine,HK,NaN,Devil May Cry 4: Special Edition
2,2015-01-01 16:22:10,d448ba963d7e1023dd1b0a40b95d4f6611750692,77ab14c1fb815e1c369ba0cf7d4c56b4fe489997,frank,GB,iphone_t,League of Legends
3,2015-01-01 03:58:13,8d6823dc52b400b50aebf269bf1f03a36d19eeaa,91cb88c0743761589273fc5e800e7743ece46494,frank,US,iphone_t,League of Legends
4,2015-01-01 11:47:35,16c1e39594d62358d27ae604ad43a071f0d86bc4,51a9234f83d656607cfd7f26690c12d2ffbce353,estelle,DE,NaN,Dota 2

In [5]:
chat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148562 entries, 0 to 148561
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   time       148562 non-null  object
 1   device_id  148560 non-null  object
 2   login      148562 non-null  object
 3   channel    148562 non-null  object
 4   country    142641 non-null  object
 5   player     37536 non-null   object
 6   game       148221 non-null  object
dtypes: object(7)
memory usage: 7.9+ MB

Lets checkout the different games we have in our dataset

In [6]:
stream['game'].unique()

array(['League of Legends', 'DayZ', 'Dota 2', 'Heroes of the Storm',
       'Counter-Strike: Global Offensive',
       'Hearthstone: Heroes of Warcraft', 'The Binding of Isaac: Rebirth',
       'Agar.io', 'Gaming Talk Shows', nan, 'Rocket League',
       'World of Tanks', 'ARK: Survival Evolved', 'SpeedRunners',
       'Breaking Point', 'Duck Game', 'Devil May Cry 4: Special Edition',
       'Block N Load', 'Fallout 3', 'Batman: Arkham Knight',
       'Reign Of Kings', 'The Witcher 3: Wild Hunt',
       'The Elder Scrolls V: Skyrim', 'Super Mario Bros.', 'H1Z1',
       'The Last of Us', 'Depth', 'Mortal Kombat X',
       'Senran Kagura: Estival Versus', 'The Sims 4',
       'You Must Build A Boat', 'Choice Chamber', 'Music', 'Risk of Rain',
       'Grand Theft Auto V', 'Besiege', 'Super Mario Bros. 3', 'Hektor',
       'Bridge Constructor Medieval', 'Lucius', 'Blackjack',
       'Cities: Skylines'], dtype=object)

In [7]:
stream['game'].nunique()

41

We're working with 41 different games here.  
Lets find out the most popular game here

In [8]:
stream['game'].value_counts()

League of Legends                   193533
Dota 2                               85608
Counter-Strike: Global Offensive     54438
DayZ                                 38004
Heroes of the Storm                  35310
The Binding of Isaac: Rebirth        29467
Gaming Talk Shows                    28115
World of Tanks                       15932
Hearthstone: Heroes of Warcraft      14399
Agar.io                              11480
Rocket League                         7087
ARK: Survival Evolved                 4158
SpeedRunners                          3367
Duck Game                             1063
Fallout 3                              485
Devil May Cry 4: Special Edition       231
Breaking Point                         161
Batman: Arkham Knight                  117
Reign Of Kings                          50
The Witcher 3: Wild Hunt                45
Block N Load                            34
Depth                                   27
Mortal Kombat X                         22
H1Z1                                     7
Super Mario Bros.                        6
Grand Theft Auto V                       5
Music                                    4
The Elder Scrolls V: Skyrim              3
The Last of Us                           3
Risk of Rain                             2
Senran Kagura: Estival Versus            2
You Must Build A Boat                    1
Choice Chamber                           1
The Sims 4                               1
Bridge Constructor Medieval              1
Hektor                                   1
Blackjack                                1
Cities: Skylines                         1
Super Mario Bros. 3                      1
Besiege                                  1
Lucius                                   1
Name: game, dtype: int64

Lets checkout which country has the most number of players playing LoL.

In [9]:
stream[stream['game']=='League of Legends'].groupby('country')['login']\
    .count().reset_index().sort_values(by='login',ascending=False)

    country  login
147      US  85606
27       CA  13034
36       DE  10835
51       GB   6964
143      TR   4412
..      ...    ...
1        AD      1
137      SN      1
136      SM      1
61       GY      1
0        A1      1

[155 rows x 2 columns]

Lets see which device is used the most for streaming

In [10]:
stream['player'].value_counts()

site             246115
iphone_t         100689
android           93508
ipad_t            53646
embed             19819
xbox_one           4863
home               3479
frontpage          1567
amazon             1155
xbox360             985
roku                233
chromecast          149
facebook             83
nvidia shield         3
ouya                  3
android_pip           2
Name: player, dtype: int64

Lets add the genre of the games to the DataFrame. The popular games. Rest will be filled as 'Other'

In [13]:
genre = {'League of Legends':'MOBA', 'Dota 2':'MOBA', 'Heroes of Storm':'MOBA',
        'Counter-Strike: Global Offensive':'FPS', 'DayZ':'Survival', 'Survival_Evolved':'Survival'}

stream['genre'] = stream['game'].map(genre)
stream['genre'].fillna('Other', inplace=True)
stream.head(10)

,time,device_id,login,channel,country,player,game,stream_format,subscriber,genre
0,2015-01-01 18:33:52,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA
1,2015-01-01 23:35:33,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False,Survival
2,2015-01-01 04:39:38,2f9c3f9ee1033b71a3819564243f20ef3bec0183,5b9a43e68f019185f55615d0b83019dee4b5d06f,frank,US,site,League of Legends,chunked,False,MOBA
3,2015-01-01 11:15:30,0cda8226ba2583424c80c3c1c22c1256b080ad17,02c7797faa4d8a3ff4b0c14ee1764b6817b53d0b,estelle,CH,site,Dota 2,high,False,MOBA
4,2015-01-01 11:28:19,e3288ca5e3153aa85e32f64cdd994b7666968dcf,b920c228acbcbebee26d9c79f6eb73b73a9480c7,morty,FR,site,Heroes of the Storm,medium,False,Other
5,2015-01-01 23:27:36,343fe2bfd58595d5c18602d420ecf6f9d694d5a8,7814f661a54349ff5eee84f9d6f476918c9b7270,george,US,iphone_t,DayZ,NaN,NaN,Survival
6,2015-01-01 21:09:23,80a0c7d1abb6a5a0060e18202b77bef831e08ca5,eb158cab3f606d3894a32e20bddbfd2d589095a9,frank,US,site,League of Legends,high,True,MOBA
7,2015-01-01 19:14:27,1e342e5e4e228f617449029054b3bb19c5224528,2aaf6a414bc3dc923b04f986de7ba1b8101c6698,frank,CA,site,League of Legends,high,False,MOBA
8,2015-01-01 13:51:04,272cffbb1a9a33ad3bb48a2ee9ae5cbcac5ca22e,401716920e3435b5e3eec9fc4ccd6a44c7af38f5,kramer,TR,site,Counter-Strike: Global Offensive,chunked,False,FPS
9,2015-01-01 22:00:14,593ed161c456eeeb9e18b8005786d42abc1a7373,ef24dc49ceb4bcd3cccb0fa862d8a150ecf935e1,frank,US,site,League of Legends,medium,False,MOBA

In [17]:
type(stream.iloc[0, 0]) # First 0 corresponds to time column, second 0 corresponds to first entry

str

The time column in stream is a string object. We have to convert it to datetime for plotting the variations in streams with respect to time

In [20]:
stream['time_dt'] = pd.to_datetime(stream['time'])
stream.head()

,time,device_id,login,channel,country,player,game,stream_format,subscriber,genre,time_dt
0,2015-01-01 18:33:52,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 18:33:52
1,2015-01-01 23:35:33,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False,Survival,2015-01-01 23:35:33
2,2015-01-01 04:39:38,2f9c3f9ee1033b71a3819564243f20ef3bec0183,5b9a43e68f019185f55615d0b83019dee4b5d06f,frank,US,site,League of Legends,chunked,False,MOBA,2015-01-01 04:39:38
3,2015-01-01 11:15:30,0cda8226ba2583424c80c3c1c22c1256b080ad17,02c7797faa4d8a3ff4b0c14ee1764b6817b53d0b,estelle,CH,site,Dota 2,high,False,MOBA,2015-01-01 11:15:30
4,2015-01-01 11:28:19,e3288ca5e3153aa85e32f64cdd994b7666968dcf,b920c228acbcbebee26d9c79f6eb73b73a9480c7,morty,FR,site,Heroes of the Storm,medium,False,Other,2015-01-01 11:28:19

In [23]:
stream_chat = pd.merge(stream, chat, on='device_id', how='outer')
stream_chat.head(20)

,time_x,device_id,login_x,channel_x,country_x,player_x,game_x,stream_format,subscriber,genre,time_dt,time_y,login_y,channel_y,country_y,player_y,game_y
0,2015-01-01 18:33:52,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 18:33:52,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
1,2015-01-01 23:11:18,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 23:11:18,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
2,2015-01-01 17:29:23,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 17:29:23,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
3,2015-01-01 16:39:05,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 16:39:05,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
4,2015-01-01 21:54:57,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 21:54:57,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
5,2015-01-01 16:56:32,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 16:56:32,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
6,2015-01-01 17:03:29,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 17:03:29,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
7,2015-01-01 20:46:12,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 20:46:12,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
8,2015-01-01 21:41:39,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 21:41:39,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
9,2015-01-01 21:18:32,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 21:18:32,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
10,2015-01-01 21:26:31,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 21:26:31,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
11,2015-01-01 17:02:18,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 17:02:18,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
12,2015-01-01 21:31:31,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 21:31:31,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
13,2015-01-01 17:42:09,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 17:42:09,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
14,2015-01-01 21:33:38,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 21:33:38,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
15,2015-01-01 17:37:03,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 17:37:03,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
16,2015-01-01 17:44:44,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,2015-01-01 17:44:44,2015-01-01 22:43:57,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
17,2015-01-01 23:35:33,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False,Survival,2015-01-01 23:35:33,2015-01-01 21:23:49,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,NaN,DayZ
18,2015-01-01 23:35:33,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False,Survival,2015-01-01 23:35:33,2015-01-01 22:00:41,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,NaN,DayZ
19,2015-01-01 23:35:33,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False,Survival,2015-01-01 23:35:33,2015-01-01 20:41:16,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,NaN,DayZ

# Visualization

1) Making a Bar Graph of which game is streamed the most